name: cight
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

  #---------------------- PACKAGES ----------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  camera: ^0.11.1
  flutter_tts: ^3.8.5
  image: ^4.0.17
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  http_parser: ^4.1.2
  loading_animation_widget: ^1.3.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  awesome_ripple_animation: ^2.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific

  #---------------------- ./ PACKAGES END ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #---------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  #---------------------- LOCAL FONTS ----------------------#
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
